medicotary/Medicotary

craco.config.js
package-lock.json
package.json
src/index.css
tailwind.config.js

Description : [Added Tailwind CSS according to the documentation](https://tailwindcss.com/docs/guides/create-react-app) 
Issue Solved : #5

Tailwind CSS Configured

---

src/components/footer.jsx
src/routes/landingpage.jsx
src/routes/vendors.jsx

fixed vendors page main content width and added footer button link

fixed vendors page and footer button

---

package-lock.json
package.json
src/config/default.config.js
src/config/reduxPersist.js
src/redux/actions/auth.action.js
src/redux/actions/index.js
src/redux/reducers/auth.reducer.js
src/redux/reducers/index.js
src/redux/sagas/auth.saga.js
src/redux/sagas/index.js
src/redux/types/auth.types.js
src/redux/types/index.js
src/routes/auth/login.jsx
yarn.lock

Initialized Redux

---

src/components/productTile.jsx
src/redux/actions/auth.action.js
src/redux/actions/vendor.actions.js
src/redux/reducers/auth.reducer.js
src/redux/reducers/vendor.reducer.js
src/redux/sagas/auth.saga.js
src/redux/sagas/product.saga.js
src/redux/sagas/vendor.sagas.js
src/redux/services/vendor.service.js
src/redux/types/auth.types.js
src/redux/types/vendor.types.js
src/routes/auth/login.jsx
src/routes/auth/signup.jsx
src/routes/products.jsx
src/routes/profile.jsx

Improved Redux [Connected to Auth]

---

src/routes/auth/login.jsx
src/routes/auth/signup.jsx
src/routes/landingpage.jsx

Added  a check for JWT token at the login page 

Token Check At Landing page

---

src/routes/auth/login.jsx
src/routes/auth/signup.jsx
src/routes/profile.jsx

This reverts commit 3ccce2dbf6f7d40672b4f21e9def760f0510ab56.

Revert "Added State Management To Auth Routes"

---

src/redux/actions/auth.action.js
src/redux/reducers/auth.reducer.js
src/redux/types/auth.types.js
src/routes/auth/login.jsx
src/routes/auth/signup.jsx
src/routes/profile.jsx

Fixed Auth Bug + Added Logout Functionality

---

src/components/sidebar.jsx
src/icons/index.js
src/icons/search.svg
src/routes/products/products.jsx
src/routes/vendors/vendors.jsx

added top nav bar in vendors and products page

---

src/routes/billing/billing.jsx
src/routes/vendors/vendors.jsx

added top bars to billing page

---

package-lock.json
package.json
src/app.jsx
src/components/LoginForm.jsx
src/components/loader.jsx
src/index.js
src/redux/actions/auth.action.js
src/redux/history.js
src/redux/reducers/auth.reducer.js
src/redux/sagas/auth.saga.js
src/redux/selector/auth.Selector.js
src/redux/services/auth.service.js
src/redux/types/auth.types.js
src/routes/auth/login.jsx
src/routes/profile.jsx
yarn.lock

Adding Store +  History + Login Fix

---

src/components/header.jsx
src/components/header_advance.jsx

Improved Headers

---

src/components/dashboard/graphs/stock-percentage.jsx
src/components/dashboard/graphs/weighted-score.jsx
src/components/dashboard/middle-section/out-of-stock-products.jsx
src/components/dashboard/middle-section/products-on-low-stock.jsx
src/components/dashboard/middle-section/products-to-be-arrived.jsx
src/components/dashboard/topbanner.jsx
src/components/sidebar/gotofaq.jsx
src/components/sidebar/quickadd.jsx
src/components/sidebar/sidebar.jsx
src/routes/billing/addBill.jsx
src/routes/billing/billing.jsx
src/routes/dashboard.jsx
src/routes/delivery/createintegration.jsx
src/routes/delivery/delivery.jsx
src/routes/products/addProduct.jsx
src/routes/products/products.jsx
src/routes/vendors/addVendor.jsx
src/routes/vendors/vendors.jsx

refactored dashboard and sidebar components

---

src/app.jsx
src/components/LoginForm.jsx
src/components/billproduct.jsx
src/components/delivery/integration-details.jsx
src/icons/index.js
src/icons/upload.svg
src/routes/auth/signup.jsx
src/routes/delivery/createintegration.jsx
src/routes/profile.jsx

create integration page completed , profile page fixed

---

src/components/forms/ProductForm.jsx
src/redux/actions/product.action.js
src/redux/reducers/product.reducer.js
src/redux/sagas/product.saga.js
src/redux/services/product.service.js
src/redux/types/product.types.js

Product Form Improved

---

package.json
src/app.jsx
src/components/forms/VendorForm.jsx
src/components/productTile.jsx
src/redux/reducers/product.reducer.js
src/redux/reducers/vendor.reducer.js
src/redux/services/product.service.js
src/redux/services/vendor.service.js
src/redux/types/vendor.types.js
src/routes/products/addProduct.jsx
src/routes/products/products.jsx
src/routes/vendors/addVendor.jsx

Fixed Product Form And Vendor Form

---

src/components/forms/ProductForm.jsx
src/components/header.jsx
src/components/header_advance.jsx
src/redux/history.js

Header Fixed

---

src/components/forms/LoginForm.jsx
src/components/forms/SignupForm.jsx
src/components/loader.jsx

login loader place in center

---

src/components/faqcard.jsx
src/routes/faqs.jsx

added content in FAQ pages

---

src/components/forms/ProfileForm.jsx

Update State of Profile

---

src/components/forms/ProfileForm.jsx
src/components/loader.jsx
src/routes/profile.jsx

neat work in profile form

---

src/components/dashboard/graphs/weighted-score.jsx
src/redux/actions/home.action.js
src/redux/actions/index.js
src/redux/reducers/home.reducer.js
src/redux/reducers/index.js
src/redux/sagas/home.sagas.js
src/redux/sagas/index.js
src/redux/services/home.service.js
src/redux/services/index.js
src/redux/types/home.types.js
src/redux/types/index.js
src/routes/dashboard.jsx

Dashboard Competed

---

package.json
src/components/forms/VendorForm.jsx
src/redux/actions/auth.action.js
src/redux/actions/index.js
src/redux/actions/user.action.js
src/redux/actions/vendor.actions.js
src/redux/reducers/product.reducer.js
src/redux/reducers/vendor.reducer.js
src/redux/sagas/product.saga.js
src/redux/sagas/vendor.sagas.js
src/redux/services/vendor.service.js
src/redux/types/auth.types.js
src/redux/types/index.js
src/redux/types/user.types.js
src/routes/vendors/vendors.jsx

Product And Vendors Completed

---

src/routes/dashboard.jsx
src/routes/notifications.jsx

Notifications done

---

src/components/forms/ProductForm.jsx
src/redux/actions/bill.action.js
src/redux/actions/index.js
src/redux/sagas/auth.saga.js
src/redux/sagas/bill.sagas.js
src/redux/sagas/index.js
src/redux/services/bill.service.js
src/redux/services/index.js
src/redux/services/user.service.js
src/redux/types/bill.types.js
src/redux/types/index.js
src/redux/types/user.types.js
src/routes/billing/addBill.jsx

Add Bill [State] Improved

---

src/routes/billing/addBill.jsx

billing functionality completed

---

src/components/forms/ProductForm.jsx

Product Form Fixed

---

src/redux/reducers/bill.reducer.js
src/redux/reducers/index.js
src/routes/billing/addBill.jsx
src/routes/billing/billing.jsx

Bill [State Management] completed

---

src/app.jsx
src/components/sidebar/sidebar.jsx
src/routes/auth/signup.jsx
src/routes/billing/billing.jsx
src/routes/billing/invoice.jsx
src/routes/delivery/createintegration.jsx
src/routes/notifications.jsx
src/routes/vendors/vendors.jsx

added invoice page frontend

---

src/app.jsx
src/components/delivery/maincard.jsx
src/index.css
src/routes/billing/addBill.jsx
src/routes/billing/billing.jsx
src/routes/billing/invoice.jsx
src/routes/delivery/createintegration.jsx
src/routes/delivery/delhivery.jsx
src/routes/delivery/delivery.jsx
src/routes/products/addProduct.jsx
src/routes/vendors/addVendor.jsx

added DHL delivery tracking page

---

src/components/forms/ProfileForm.jsx
src/components/header.jsx
src/redux/services/user.service.js

User Form Data Updating

---

src/components/forms/ProductForm.jsx
src/components/productTile.jsx

added preffered vendor dropdown

---

package-lock.json
package.json
src/app.jsx
src/components/forms/EditProductForm.jsx
src/components/forms/ProfileForm.jsx
src/components/productTile.jsx
src/icons/index.js
src/icons/log-out.svg
src/index.css
src/routes/billing/billing.jsx
src/routes/products/editProduct.jsx
yarn.lock

added custom bill and product routes

---

src/app.jsx
src/components/forms/EditVendorForm.jsx
src/routes/vendors/editVendor.jsx
src/routes/vendors/vendors.jsx

added custom routes to edit vendor

---

src/components/billing/invoice.jsx
src/components/forms/ProfileForm.jsx
src/routes/billing/billing.jsx

bill products are not showing up 😭😭

---

src/components/billing/invoice.jsx
src/components/forms/ProfileForm.jsx
src/routes/billing/billing.jsx
src/routes/dashboard.jsx

Bill View Completed
